# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_course_arrangement?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 热部署配置
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  #设置文件传输大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis-plus:
  mapper-locations: classpath:/mapper/xml/*Mapper.xml
  typeAliasesPackage: com.lyk.coursearrange.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 #删除
      logic-not-delete-value: 0 #不删除

server:
  port: 8080


# 卓正软件
key: IMTG6-BSXJ-JGZ6-3BIWM
poSysPath: D:/arrange/license/
password: 111111

# 阿里云OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: LTAI4FgC4srdFY4KPjYNVx1u
      accessKeySecret: IKoCvPxq7aMX4Bh9revMk7z30fjqP1
      bucketName: arrange